export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const REQUEST_RECENT_TRACKS = 'REQUEST_RECENT_TRACKS';
export const FAIL_RECENT_TRACKS = 'FAIL_RECENT_TRACKS';
export const GOT_RECENT_TRACKS = 'GOT_RECENT_TRACKS';
export const LOADING_FILTER_DATA = 'LOADING_FILTER_DATA';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
export const SET_USER_MESSAGE = 'SET_USER_MESSAGE';
export const FILTER_DATA_LOADING = 'FILTER_DATA_LOADING';
export const SUCCESS_CONFIRM = 'SUCCESS_CONFIRM';
export const FAIL_CONFIRM = 'FAIL_CONFIRM';

export const USERS_DATA_LOADING = 'USERS_DATA_LOADING';
export const USERS_DATA_LOADING_DATA_SUCCESS = 'USERS_DATA_LOADING_DATA_SUCCESS';
export const USERS_DATA_LOADING_DATA_FAILURE = 'USERS_DATA_LOADING_DATA_FAILURE';
export const SET_USERS = 'SET_USERS';
export const SET_USER_AUTH = 'SET_USER_AUTH';

export const USERS_CHAT_DATA_LOADING = 'USERS_CHAT_DATA_LOADING';
export const USERS_CHAT_DATA_LOADING_DATA_SUCCESS = 'USERS_CHAT_DATA_LOADING_DATA_SUCCESS';
export const USERS_CHAT_DATA_LOADING_DATA_FAILURE = 'USERS_CHAT_DATA_LOADING_DATA_FAILURE';
export const USERS_CHAT_ADD_OWN_CHAT = 'USERS_CHAT_ADD_OWN_CHAT';
export const USERS_CHAT_RESET_STATE = 'USERS_CHAT_RESET_STATE';

export const PROFILE_DATA_LOADING = 'PROFILE_DATA_LOADING';
export const PROFILE_DATA_LOADING_DATA_SUCCESS = 'PROFILE_DATA_LOADING_DATA_SUCCESS';
export const PROFILE_DATA_LOADING_DATA_FAILURE = 'PROFILE_DATA_LOADING_DATA_FAILURE';

export const apiURL = 'http://178.20.156.208:4000';
//export const apiURL = 'http://localhost:4000';
